server:
  port: 8081

jwt:
  secret: chiaveSuperSegretaPerJWT1234567890abcdef12
  expiration: 86400000  # 24 ore in millisecondi

spring:
  application:
    name: utenti-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: utenti_user
    password: utenti123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true